# Generated by Django 2.2.2 on 2019-07-03 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('cover', models.ImageField(upload_to='')),
                ('status', models.IntegerField()),
                ('description', models.TextField()),
                ('publish_date', models.DateTimeField()),
                ('ISBN', models.CharField(max_length=191)),
                ('pages', models.IntegerField()),
                ('print_mode', models.CharField(max_length=191)),
                ('book_size', models.CharField(max_length=191)),
                ('publish_status', models.CharField(max_length=191)),
                ('origin_name', models.CharField(max_length=191)),
                ('origin_ISBN', models.CharField(max_length=191)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('author', models.ManyToManyField(related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BookTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=191)),
                ('publish_date', models.DateTimeField()),
                ('recommend_times', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ituring.Book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='book_category_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ituring.BookCategory'),
        ),
        migrations.AddField(
            model_name='book',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(to='ituring.BookTag'),
        ),
        migrations.AddField(
            model_name='book',
            name='translator',
            field=models.ManyToManyField(related_name='translator', to=settings.AUTH_USER_MODEL),
        ),
    ]
