# Generated by Django 2.2.2 on 2019-07-03 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ituring', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='book_id',
            new_name='book',
        ),
    ]
